### ISSUE TITLE
css中的居中方案

### ISSUE THREAD

**Issue by jo0ger** [jo0ger/jooger.me-source#4]
css居中可谓是老生常谈了，今天来简单地介绍几个我知道的居中方案，其中包含
1. 水平居中
2. 垂直居中
3. 水平垂直居中

<style>
  .demo {
    margin-bottom: 30px;
    padding-bottom: 10px;
    color: #fff;
    border-bottom: 1px dashed #0085a1;
  }
  .title {
    color: #333;
      padding: 0 10px 10px;
      text-align: center;
  }
  .parent {
    position: relative;
    width: 100%;
    height: 200px;
    background-color: #f7f7f7;
  }
  .child {
    position: inherit;
    width: 100px;
    height: 100px;
    padding: 10px;
    background-color: #0085a1;
  }
  .parent:before, .child:before {
    content: attr(data-tip);
    position: absolute;
    bottom: 0;
    right: 0;
    padding: 5px;
    font-weight: 700;
    font-size: 18px;
  }
  .parent:before {
    color: #0085a1;
  }
</style>

css居中可谓是老生常谈了，今天来简单地介绍几个我知道的居中方案

（以下例子中的父元素的class为parent，子元素的class为child）

### 分类

我将居中问题分为以下几类：

* 水平居中
  * 宽未知元素
  * 常规文档流元素
    * 行内元素（inline）
    * 块元素（block）
  * 脱离文档流元素
    * 浮动元素（float）
    * 绝对定位元素（absolute）
* 垂直居中
  * 高未知元素
  * 高已知元素
  * 单行文本元素
* 水平垂直居中
  * 绝对定位居中方法
  * 负边距方法
  * transform布局方法
  * flex布局方法
  * table-cell布局方法

#### 宽未知元素

有两种方法，**transform**和**flex**方法

* **transform**

``` css
.parent {
  position: relative;
}
.child {
  position: absolute;
  left: 50%;
  transform: translateX(-50%);
}
```

demo：

<div class="demo h-1 h-1-t"><div class="parent" data-tip="parent"><div class="child" data-tip="child"></div></div></div>

<style>
  .demo.h-1 .child {
    width: auto;
    padding: 30px;
  }
  .demo.h-1-t .child{
    position: absolute;
    left: 50%;
    transform: translateX(-50%);
  }
</style>

* **flex**

``` css
.parent {
  display: flex;
  justify-content: center;
}
```

demo：

<div class="demo h-1 h-1-f"><div class="parent" data-tip="parent"><div class="child" data-tip="child"></div></div></div>

<style>
  .demo.h-1-f .parent {
    display: flex;
    justify-content: center;
  }
</style>

##### 行内元素（inline）

``` css
.parent {
  text-align: center;
}
```

demo:
<div class="demo h-2 h-2-i"><div class="parent" data-tip="parent"><span class="child" data-tip="child">child</span></div></div>

<style>
  .demo.h-2-i .parent {
    text-align: center;
  }
  .demo.h-2-i .child {
    padding: 5px;
  }
  .demo.h-2-i .child:before {
    display: none;
  }
</style>

> display: inline-block;的元素也可以用此方法水平居中

##### 块元素（block）

此时元素width已知

``` css
.child {
  width: 100px;
  margin: 0 auto;
}
```

demo:

<div class="demo h-2 h-2-b"><div class="parent" data-tip="parent"><div class="child" data-tip="child"></div></div></div>

<style>
  .demo.h-2-b .child {
    width: 100px;
    margin: 0 auto;
  }
</style>

> 正如上述所说，将child的display设置为inline-block，然后parent的text-align：center也可以实现居中，这里就不写代码了

#### 脱离文档流元素

此时元素width已知

##### 浮动元素（float）

``` css
.child {
  float: left;
  width: 100px;
  left: 50%;
  margin-left: -50px;
}
```

demo:

<div class="demo h-3 h-3-f"><div class="parent" data-tip="parent"><div class="child" data-tip="child"></div></div></div>

<style>
  .demo.h-3-f .child {
    float: left;
    left: 50%;
    width: 100px;
    margin-left: -50px;
  }
</style>

##### 绝对定位元素（absolute）

方法一：只需将上面的float: left换成position: absolute就行，就不写代码了

方法二：

``` css
.parent {
  position: relative;
}
.child {
  position: absolute;
  width: 100px;
  left: 0;
  right: 0;
  margin: 0 auto;
}
```

demo:

<div class="demo h-3 h-3-a"><div class="parent" data-tip="parent"><div class="child" data-tip="child"></div></div></div>

<style>
  .demo.h-3-a .child {
    position: absolute;
    width: 100px;
    left: 0;
    right: 0;
    margin: 0 auto;
  }
</style>

#### 高未知元素

同`水平居中`的`宽未知元素`

有两种方法，**transform**和**flex**方法

* **transform**

``` css
.parent {
  position: relative;
}
.child {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
}
```

demo：

<div class="demo v-1 v-1-t"><div class="parent" data-tip="parent"><div class="child" data-tip="child"></div></div></div>

<style>
  .demo.v-1 .child {
    height: auto;
    padding: 30px;
  }
  .demo.v-1-t .child{
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
  }
</style>

#### 高已知元素

同`水平居中`的`绝对定位元素（absolute）`

方法一：

``` css
.child {
  position: absolute;
  height: 100px;
  top: 50%;
  margin-top: -50px;
}
```

demo: 

<div class="demo v-2 v-2-1"><div class="parent" data-tip="parent"><div class="child" data-tip="child"></div></div></div>

<style>
  .demo.v-2-1 .child {
    position: absolute;
    height: 100px;
    top: 50%;
    margin-top: -50px;
  }
</style>

方法二：

``` css
.parent {
  position: relative;
}
.child {
  position: absolute;
  height: 100px;
  top: 0;
  bottom: 0;
  margin: auto 0;
}
```

demo:

<div class="demo v-2 v-2-2"><div class="parent" data-tip="parent"><div class="child" data-tip="child"></div></div></div>

<style>
  .demo.v-2-2 .child {
    position: absolute;
    height: 100px;
    top: 0;
    bottom: 0;
    margin: auto 0;
  }
</style>

#### 单行文本元素

``` css
.child {
  
}
```

demo:

<div class="demo v-3 v-3-s"><div class="parent" data-tip="parent"><span class="child" data-tip="child"></span></div></div>

<style>
  .demo.v-3 .child {
    height: 200px;
    line-height: 200px;
    padding-left: 50px;
  }
  .demo.v-3 .child:before {
    bottom: auto;
  }
</style>

> 将line-height设置与父容器height相同，不过这种方法只适用于单行文本

### 水平垂直居中

综合上面两种居中，可以得出以下几种方案

#### 绝对定位居中方法

综合`水平居中`的`绝对定位元素（absolute）`和`垂直居中`的`高已知元素`

``` css
.parent {
  position: relative;
}
.child {
  position: absolute; // fixed也行
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  margin: auto;
  width: 100px;
  height: 100px;
}
```

demo:

<div class="demo hv-1"><div class="parent" data-tip="parent"><div class="child" data-tip="child"></div></div></div>

<style>
  .demo.hv-1 .parent {
    position: relative;
  }
  .demo.hv-1 .child {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    margin: auto;
    width: 100px;
    height: 100px;
  }
</style>

> 不仅兼容性很好，而且支持width和height设置成百分比，以及max-*和min-*（我最喜欢的方案之一）

#### 负边距方法

``` css
  .demo.hv-1 .parent {
    position: relative;
  }
  .demo.hv-1 .child {
    position: absolute;
    top: 50%;
    left: 50%;
    margin-top: -50px;
    margin-left: -50px;
    width: 100px;
    height: 100px;
  }
```

demo:

<div class="demo hv-2"><div class="parent" data-tip="parent"><div class="child" data-tip="child"></div></div></div>

<style>
  .demo.hv-2 .parent {
    position: relative;
  }
  .demo.hv-2 .child {
    position: absolute;
    top: 50%;
    left: 50%;
    margin-top: -50px;
    margin-left: -50px;
    width: 100px;
    height: 100px;
  }
</style>

> 缺点是不支持设置width和height为百分比，而且也不支持max-*和min-*属性，不过兼容性还是很好的

#### transform布局方法

个人最喜欢的方案之一

``` css
.parent {
  position: relative;
}
.child {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```

demo:

<div class="demo hv-3"><div class="parent" data-tip="parent"><div class="child" data-tip="child"></div></div></div>

<style>
  .demo.hv-3 .parent {
    position: relative;
  }
  .demo.hv-3 .child {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
  }
</style>

#### flex布局方法

css3新增的属性，虽然现在兼容性稍微有问题，但是可以hack解决，毕竟是css布局的大趋势，可以省很多功夫

``` css
.parent {
  display: flex;
  justify-content: center;
  align-items: center;
}
```

demo:

<div class="demo hv-4"><div class="parent" data-tip="parent"><div class="child" data-tip="child"></div></div></div>

<style>
  .demo.hv-4 .parent {
    display: flex;
    justify-content: center;
    align-items: center;
  }
</style>

> 至于hack方式，可以自行google

#### table-cell布局方法

这个我很少用，主要是不想看见table这个单词->_->

``` css
.parent {
  display: table-cell;
  vertical-align: middle;
  text-align: center;
  width: 200px;
  height: 200px;
}
.child {
  display: inline-block;
  width: 100px;
  height: 100px;
}
```

demo:

<div class="demo hv-5"><div class="parent" data-tip="parent"><div class="child" data-tip="child"></div></div></div>

<style>
  .demo.hv-5 .parent {
    display: table-cell;
    vertical-align: middle;
    text-align: center;
    width: 200px;
    height: 200px;
  }
  .demo.hv-5 .child {
    display: inline-block;
    width: 100px;
    height: 100px;
  }
</style>

> 需要知道parent的width和height，在parent里不支持width百分比，而且只适用于child是inline和inline-block的元素

以后遇到新的会继续更新...

以上
